### ISSUE TITLE
add `level` option to ipfs.dag.tree

### ISSUE THREAD

**Issue by wanderer** [ipfs/interface-js-ipfs-core#137]
a `level` options would specify the number of levels to fetch in a `tree`. This could replace the recusive options. Since you could (in JS) use `Infinity`

This type of thing was implemented in [js-ipld-graph-builder](https://github.com/ipld/js-ipld-graph-builder/blob/master/index.js#L120-L143) 

@jbenet @diasdavid

**Comment by diasdavid** [comment]
@vmx ^^
