### ISSUE TITLE
Key Value Store API

### ISSUE THREAD

**Issue by daviddias** [ipfs/interface-js-ipfs-core#157]
Following https://github.com/protocol/lab-week-unconf/issues/18#issuecomment-333881446

@pgte can you take the first stab and lead the development of this API for IPFS?

**Comment by diasdavid** [comment]
@pgte any update here? Do you think that we can have something out soon?

**Comment by pgte** [comment]
@diasdavid been short on time lately, plan to work on this this following week.

**Comment by achingbrain** [comment]
This issue is very stale, please open a new issue on ipfs/js-ipfs if we still want to do this.
