### ISSUE TITLE
Test object.patch.rmLink cannot be run in isolation

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interface-js-ipfs-core#189]
I was trying to run this test using `it.only` but couldn't. It's because it depends on the output from `object.patch.addLink`.

It requires [`testNodeWithLinkMultihash` and `testLink`](https://github.com/ipfs/interface-ipfs-core/blob/master/src/object.js#L744) which are first defined in the [`.addLink` test](https://github.com/ipfs/interface-ipfs-core/blob/master/src/object.js#L697).

**Comment by diasdavid** [comment]
@alanshaw wanna submit a PR to make sure that the test does what it needs to be able to run in isolation?

**Comment by alanshaw** [comment]
It's on my stack

**Comment by achingbrain** [comment]
I think this has been done, please open a new issue against ipfs/js-ipfs if there's still a problem.
