### ISSUE TITLE
files.get spec should accept a cid instance

### ISSUE THREAD

**Issue by jacobheun** [ipfs/interface-js-ipfs-core#247]
files.get spec does not allow users to pass a cid instance, only buffers and paths. This should be added to match the [files.cat spec](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#javascript---ipfsfilescatipfspath-callback)

**Comment by alanshaw** [comment]
Looking at the js-ipfs and js-ipfs-api code it looks like this might actually already be possible. Would you be willing to send a PR updating the spec doc and adding a test?

**Comment by jacobheun** [comment]
I won't be able to get to it for at least a couple of weeks due to other priorities. This would be a good starter issue for someone. I've added the `help wanted` label for now, in addition to the others you already added. It's entirely possible this is already working and there is just inconsistency in the SPEC.
