### ISSUE TITLE
files.add*Stream coverage is poor

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interface-js-ipfs-core#292]
Pulling out tests per command for https://github.com/ipfs/interface-ipfs-core/pull/290 shows that test coverage for `addReadableStream` and `addPullStream` is poor (almost non existent).

Considering `files.add` is basically most developer's first port of call when starting with IPFS these commands should be rock solid and tested as such.

**Comment by achingbrain** [comment]
This code has mostly been deleted with the async/await refactor, so I don't think there's much to do here now - please open an issue on ipfs/js-ipfs if that's not the case.
