### ISSUE TITLE
Speed up DHT tests

### ISSUE THREAD

**Issue by victorb** [ipfs/interface-js-ipfs-core#351]
It seems that currently, the DHT tests are running very slowly. We should find ways of speeding them up, as they add lots of time to the running time of both js-ipfs and js-ipfs-api.

Here is a list from CI with the slowest cases from js-ipfs-api:
![image](https://user-images.githubusercontent.com/459764/44022668-8b8fb022-9ee8-11e8-9641-e6c1df65142c.png)

https://ci.ipfs.team/view/JavaScript/job/IPFS/job/js-ipfs-api/job/master/140/testReport/(root)/interface-ipfs-core%20tests/

**Comment by achingbrain** [comment]
The code behind these tests has changed a lot since this issue was opened.  Closing for now.
