### ISSUE TITLE
ipfs.files.add size

### ISSUE THREAD

**Issue by achingbrain** [ipfs/interface-js-ipfs-core#387]
With the following code:

```javascript
ipfs.files.add({
  path: '/foo.txt',
  content: <data>
}, (error, result) => {
  console.info(result)
// [{
//  path: '/foo.txt,
//  hash: 'QmHash', // base58 encoded multihash
//  size: 123
// }]
})
```

The returned `size` property is the size of the DAGNode (or tree of nodes) that contain the file data, including protobuf overhead, etc.  Do people find this useful?  I was surprised on first use that it wasn't the size of the file added (which would also have been redundant - I've just added the file, I know how big it is).

Perhaps this property should be removed and instead a `ipfs dag stat <cid>` command introduced similar to `ipfs files stat <path>` that gives you that sort of information about the DAG for a given hash?

The `ipfs.files.stat` implementation could even just resolve the path to a cid and then chain through to `ipfs.dag.stat`.

**Comment by vmx** [comment]
As a "thumbs up" could be misleading, I post a comment. I'd in favour of removing it, I'm a fan of small API surfaces.

**Comment by achingbrain** [comment]
This API has changed quite a lot, the returned size is now the file size so I'm going to close this.
