### ISSUE TITLE
RFC: Do not return string CIDs from core

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interface-js-ipfs-core#394]
The following core API functions (in JS at least) return multibase encoded string CIDs:

* [x] `bitswap.wantlist`
* [x] `bitswap.stat`
* [x] `block.stat`
* [x] `block.rm`
* [x] `add`
* [x] `files.ls`
* [x] `files.stat`
* [x] `object.stat`
* [x] `pin.add`
* [x] `pin.rm`
* [x] `pin.ls`

Core should not make any assumptions about the what base encoding we'd like our CIDs in or even if we want them encoded as strings. They should all return [CID](https://github.com/ipld/js-cid) instances.

This would make these APIs consistent with the other APIs and would save a bunch of CID -> string -> CID conversion that's happening at the moment and all the overhead that brings with it.

Thoughts? @achingbrain @hugomrdias @daviddias @Stebalien

**Comment by Stebalien** [comment]
This is talking about the CoreAPI, not the HTTP API, right? If so, absolutely (well, mostly). Go actually returns special "path" objects in many cases.

**Comment by daviddias** [comment]
💯
