### ISSUE TITLE
RFC: Support ArrayBuffer as an alternative to Buffer input argument

### ISSUE THREAD

**Issue by lidel** [ipfs/interface-js-ipfs-core#404]
## Status

Right now we accept `cid`, `multihash` and `data` as `Buffer` in various places across entire JS API.  It makes sense for Node.js  and there was no better alternative for use in browsers at a time.

The landscape changed and we now have [native vendor support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Browser_compatibility) for  [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) in web browsers:

>  The [`ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) object is used to represent a generic, fixed-length raw binary data buffer. You cannot directly manipulate the contents of an `ArrayBuffer`; instead, you create one of the [typed array objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects) or a [`DataView` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView)  which represents the buffer in a specific format, and use that to read and write the contents of the buffer.

## Proposed API Improvement

Short and sweet: 

 - Add support for `ArrayBuffer` as input in every API that accepts `Buffer` right now. 

Why? 

- Low risk, High win:
  - This is backward-compatible change (`Buffer` support remains)
  - Should be a relatively small change (internally detect and convert `ArrayBuffer` to `Buffer` for now)  
  - DRY: removes the need of tedious type conversion of various inputs 
  - enables browser console experimentation without need for `Buffer` polyfil
  - Together with [Async Iterators](https://github.com/ipfs/js-ipfs/issues/1670) makes JS API feel modern an more attractive to developers

## Refs
- [MDN: `ArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)  ([browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Browser_compatibility))
- [MDN: `TypedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects) ([browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Browser_compatibility))

cc @alanshaw

**Comment by alanshaw** [comment]
We've had multiple issues opened about this. People expect to be able to use them, are confused when they cannot and _also_, do not understand the difference between them and `Buffer`.

**Comment by vmx** [comment]
I'm in favour of it.

Side note: It's also something that came to my mind. I'm thinking about using `ArrayBuffer` for the new IPLD APIs. For input it's easy, you can support both. But for return values you have to make the call whether to return `Buffer` or `ArrayBuffer`.

**Comment by lidel** [comment]
@achingbrain are you able to unpack that idea?  Do you mean objects with length and indexed items being `Buffer` or `ArrayBuffer`?

**Comment by achingbrain** [comment]
This has been implemented - if there are more formats to support, please open a PR against js-IPFS with a failing test for the `src/files/normalise-input` function in `ipfs-utils` - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-utils/test/files/normalise-input.spec.js
