### ISSUE TITLE
Testing in the JS IPFS Project

### ISSUE THREAD

**Issue by travisperson** [ipfs/interface-js-ipfs-core#406]
I want to start a discussion around testing, particularly around some of the JavaScript projects (`js-ipfs` `interface-ipfs-core` `js-ipfs-api`), really anything that requires the use of an IPFS daemon running (consumes `js-ipfsd-ctl`).

I'm curious if there are any particular testing strategies someone is trying to drive in the `js-ipfs` project at the moment, or if it's more adhoc and we can start to discuss the way we want to approach testing here in this issue.

In the `js-ipfs` project there are four main testing suites that cover the four main interfaces of the project.

+ `core`
+ `http`
+ `gateway`
+ `cli`

I want to ultimately help contributors know when they should write tests in each suite, and provide documentation and tools to help everyone write great tests that provide value to the community and project.

All of the tests suites currently require running a full node by either instantiating the core module, or starting a daemon and talking to it through `js-ipfs-api`.

A great depiction of this can be found in the `js-ipfs` readme.

![](https://github.com/ipfs/js-ipfs/raw/master/img/overview.png)

I took some time and benchmarked the `node:*` test commands for the `js-ipfs` project.

| Test Run | core       | http       | gateway   | cli         | Total       |
| -------- | ----------:| ----------:| ---------:| -----------:| -----------:|
| 1        | 24.40s     | 113.33s    | 3.88s     | 491.06s     | **632.67s** |
| 2        | 23.52s     | 114.36s    | 5.13s     | 501.95s     | **644.96s** |
| 3        | 24.39s     | 114.07s    | 6.98s     | 491.91s     | **637.35s** |
| 4        | 24.98s     | 112.91s    | 5.07s     | 491.04s     | **634.00s** |
| 5        | 23.86s     | 113.06s    | 5.59s     | 490.48s     | **632.99s** |
| 6        | 23.86s     | 114.57s    | 5.29s     | 492.69s     | **636.41s** |
| 7        | 22.40s     | 113.37s    | 8.79s     | 493.52s     | **638.08s** |
| 8        | 23.83s     | 113.34s    | 9.97s     | 498.46s     | **645.60s** |
| 9        | 21.07s     | 114.43s    | 5.66s     | 482.90s     | **624.06s** |
| 10       | 22.11s     | 114.49s    | 4.60s     | 506.10s     | **647.30s** |
| **Avg**  | **23.44s** | **113.80s**| **6.10s** | **494.01s** | **637.34s** |

From the table above we can see that the `cli` tests take the large majority of the time (though about 180s of this time is consumed by three tests, more info @ [ipfs/jenkins#93](https://github.com/ipfs/jenkins/issues/93)).

The high test time makes sense given some details about what the cli tests are doing.

+ Most are executed twice, online (with a daemon through the http-api), offline (directly to core)
+ Commands are execute through a shell, executing a new process for each command

## Some questions

The `js-ipfs` project has some sharness tests, though they haven't really been touched for years. It would appear that running cli test through node is the standard for the project. Should we remove the sharness tests?

Both the http-api and core are primarily tested through the `interface-ipfs-core` project. There are also some independent tests written out in the `core` and `http-api` folders. Should we strive to migrate these tests to the `interface-ipfs-core` project over time as features settle?

Do we see value in the `cli` tests as they are written at the moment, and do we believe we want to keep moving forward with the general approach currently loosely laid out in the tests?

/cc @diasdavid @VictorBjelkholm 

I will be responding shortly to this issue with some of my own thoughts.

**Comment by achingbrain** [comment]
This issue is quite stale, our testing regime has altered significantly since it was opened.  Please open an issue on ipfs/js-ipfs if further exploration is needed.
