### ISSUE TITLE
Consider per-language core-interface repos

### ISSUE THREAD

**Issue by magik6k** [ipfs/interface-js-ipfs-core#423]
Go implementation of core-interface (CoreAPI) is getting to the stage where it can be extracted from go-ipfs repo, and afaik it's supposed to live it this repo together with js interface definitions / tests.

But there are problems:
* Both NPM and GX use `package.json`
* Many tools expect `package.json` to live in repository root (things like gx-workspace, our Jenkins pipelines)
* Packages will carry unnecessary bloat (this can probably be mitigated)
* This will only get worse with more languages

I'd say that this repo should stay focused on JS, and interface repos should be called `[lang]-ipfs-interface`

@alanshaw @Stebalien @daviddias (+others) Thoughts?

**Comment by Stebalien** [comment]
I tend to agree. It may make sense to have a single repo for interface design/documentation but having multiple implementations in a single repo seems a bit odd.

**Comment by alanshaw** [comment]
+1

**Comment by daviddias** [comment]
Seems that we have consensus. Wanna take this on? 

Pinging @vasco-santos @jacobheun to update the libp2p ones as well (note, we can keep the package name)

**Comment by magik6k** [comment]
So `interface-go-ipfs`? I'll handle Go side soon, after https://github.com/ipfs/go-ipfs/pull/5969 and one other PR with minor fixes.

**Comment by daviddias** [comment]
`interface-go-ipfs-core` to be exact (HTTP API and CLI are the other APIs)

**Comment by jacobheun** [comment]
@daviddias just to clarify, the goal is to have, for example, `interface-stream-muxer` be a language agnostic repo for design/docs and we would create `interface-js-stream-muxer` with the current content, except the go information?

**Comment by alanshaw** [comment]
Repo renamed and PR here for moving stuff in `js/` dir back to root: https://github.com/ipfs/interface-js-ipfs-core/pull/435

**Comment by Stebalien** [comment]
@daviddias any reason to do `interface-[lang]-[name]` instead of `[lang]-[name]-interface`? We have quite a few packages following the latter convention.

**Comment by alanshaw** [comment]
I'm ok with that also, in fact I think I prefer it - so it would be `js-interface-ipfs-core` and `go-interface-ipfs-core` for example.

**Comment by Stebalien** [comment]
Yes but @daviddias asked for the current naming scheme so I'd like to get his reasoning before we rename again.

**Comment by daviddias** [comment]
We've been using `interface-*` since 2015 in multiple places https://github.com/libp2p?utf8=%E2%9C%93&q=interface-&type=&language=, that's pretty much my reasoning.

**Comment by alanshaw** [comment]
Shall we close this? https://github.com/ipfs/interface-go-ipfs-core exists now.
