### ISSUE TITLE
Make the size field of ls correspond to to the size of the file

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interface-js-ipfs-core#427]
Currently, the size returned by `ls` is the size of the *DAG* under the link (using `link.Size`). However, most users will expect `ipfs ls /some/directory` to list the sizes of the files (as returned by `ipfs cat /some/directory/file | wc -b`).

Proposal:

1. Return a 0 (-1?) size for directories. Directory sizes really don't make sense.
2. Return the actual file size for files. That is, the size stored in the file's `filesize` field.

I highly doubt this will break any existing projects. Really, it's more likely to fix hidden bugs than it is to cause them.

See: https://github.com/ipfs/go-ipfs/pull/5906#issuecomment-452382417

**Comment by magik6k** [comment]
> Return a 0 (-1?)
I'd make it 0 as some things may expect uint

**Comment by Stebalien** [comment]
@magik6k will omitting them be fine? We could also use the DAG size for directories (given that we can do whatever we want, really).

Historical note from @whyrusleeping: `ipfs ls` was *originally* supposed to be used for both files and merkledag objects (pre IPLD). `ipfs file ls` was supposed to be the command for listing *files*. However, that no longer really applies.

**Comment by magik6k** [comment]
I'd keep directory sizes in the response json, just not display them on the client

**Comment by kevina** [comment]
> I'd keep directory sizes in the response json, just not display them on the client

Is there a reason foe this?

**Comment by Stebalien** [comment]
> I'd keep directory sizes in the response json, just not display them on the client

Ideally, the user would be able to disable both `--size` and `--resolve-type` to avoid fetching the root block of every file in the directory.

**Comment by djdv** [comment]
Relevant: https://github.com/ipfs/go-ipfs/issues/5325

**Comment by alanshaw** [comment]
@achingbrain do you have any bandwidth to pick this up and restore interop?

**Comment by alanshaw** [comment]
This was fixed by https://github.com/ipfs/js-ipfs-unixfs-exporter/pull/20 and will be released in js-ipfs 0.35
