### ISSUE TITLE
Ensure all arguments to ipfs.add are documented

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interface-js-ipfs-core#429]
The `trickle` option is supported but not document. Add this option and verify all other available options are also documented.

**Comment by Prabhakar-Poudel** [comment]
@alanshaw 
I'm on it.

Few clarifications needed:
* What is the current default cidBase?
* CLI version has (quite, quieter and silent), do they exist in web version also?

Is there any reference point in the codebase which can be looked up for the same. I could not find much so I am referencing CLI version and scraping other parts.
