### ISSUE TITLE
adding unsubscribe(eventName) 

### ISSUE THREAD

**Issue by Isan-Rivkin** [ipfs/interface-js-ipfs-core#436]
Hi, currently `unsubscribe` method must take a reference to the `handler` and it forces me to keep a reference to it while it may not be ideal for some implementations. 
Maybe `unsubscribe(eventName)` could be provided based on [EventEmitter.removeAllListeners(eventName)](https://nodejs.org/api/events.html#events_emitter_removealllisteners_eventname) and how `floodsub` is implemented (inherits EventEmitter). 
I don't mind creating PR for this, just wonder if there's an issue with that first,

**Comment by alanshaw** [comment]
I think that's a good suggestion. We'd need a few PRs to make this happen:

1. PR to add a test in this repo and update the documentation
2. PR to `js-libp2p` https://github.com/libp2p/js-libp2p/blob/4ed5c039fc8583b62cb1e41284a025f5d8d258bc/src/pubsub.js#L41 to call `removeAllListeners` instead if `handler == null`
2. PR to `ipfs-http-client` to do the same thing https://github.com/ipfs/js-ipfs-http-client/blob/bfd71c2bd9a467b166c85eaa7dd5d7fb94e4dfa4/src/pubsub.js#L80

@jacobheun @vasco-santos is that cool with you?

**Comment by jacobheun** [comment]
> @jacobheun @vasco-santos is that cool with you?

Yes, this sounds great.

**Comment by Isan-Rivkin** [comment]
moved to PR #437
