### ISSUE TITLE
Undocumented key.info

### ISSUE THREAD

**Issue by AlbertoElias** [ipfs/interface-js-ipfs-core#439]
There's a useful function implemented in js-ipfs `ipfs.key.info` which isn't documented: https://github.com/ipfs/js-ipfs/blob/master/src/core/components/key.js#L14

**Comment by tapaswenipathak** [comment]
Hi @AlbertoElias: Can I work on the ticket?

**Comment by alanshaw** [comment]
There's no consensus on this function existing. It does not exist in the go-ipfs implementation and whilst it is implemented in core for JS IPFS, there's no CLI method of calling it and it is not available from the HTTP API either - nore does https://github.com/ipfs/js-ipfs-http-client implement it.

So unfortunately this isn't simply a case of documenting an existing function.

I suggest using `key.list` and find the key by name from the array that is returned.

**Comment by tapaswenipathak** [comment]
Ack, ok.
