### ISSUE TITLE
Add `pin` option to dag.put

### ISSUE THREAD

**Issue by joeltg** [ipfs/interface-js-ipfs-core#456]
Right now you can stick a boolean `pin` property in the options argument to `ipfs.add` (and addReadableStream, etc), but there's no equivalent for `ipfs.dag.put`. This is awkward if you want to selectively pin or not pin your IPLD nodes and amounts to two-step `ipfs.dag.put(object, options).then(cid => shouldWePinThis && ipfs.pin.add(cid.toString())` construction.

Not sure if this is the appropriate place to raise this issue but thought I'd bring it up here.

**Comment by alanshaw** [comment]
This was implemented in https://github.com/ipfs/js-ipfs/pull/2521
