### ISSUE TITLE
Events on peer connect and disconnect

### ISSUE THREAD

**Issue by KrishnaPG** [ipfs/interface-js-ipfs-core#475]
Does the Swarm class provide events when a peer is successfully connected and disconnected? 

It looks like `ipfs` is already an `EventEmitter` object, and raising swarm events on peer connectivity allows the `js-ipfs` apps to monitor the peer activity.

The other option is, making the `self._peerInfoBook` a reactive variable (not sure if it already is). This will make it possible to bind that variable directly to UI list controls in, say Vue / React.js that allows to build real-time updating UI of peers with much ease (which is very useful for beginners to understand / visualize what is going on under the hood, and also debug purposes).

**Comment by olizilla** [comment]
The challenge here is the js interface is used by both js-ipfs, a full implemenation of ipfs in javascript, and js-ipfs-http-client, which is used to talk to the http api of a seperate ipfs daemon. js-ipfs could offer a reactive / evented api, but the current http api doesn't support anything other than standard http request / response. No web-sockets, no server-sent events.

There is work underway to rethink how the http client works, and there is desire to upgrade the http api to support simpler ways for clients to keep up to date with changing data, but it's not something the core team will be tackling soon. We'd welcome prototypes and proposals from the community!

**Comment by alanshaw** [comment]
If you want to do this programmatically in JS IPFS you can use:

```js
ipfs.libp2p.on('peer:connect', peerInfo => {})
ipfs.libp2p.on('peer:disconnect', peerInfo => {})
```

https://github.com/libp2p/js-libp2p#events

**Comment by KrishnaPG** [comment]
Thank you @alanshaw  Looks like the libp2p events can help. Will look into it.
