### ISSUE TITLE
cat function how to get the filename using hash

### ISSUE THREAD

**Issue by yehia67** [ipfs/interface-js-ipfs-core#512]
Assume I had pushed 'fileName.txt' using ipfs.add() and got hash 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'. Now I want to use cat() function to get the file name from the hash  'xxxxxxxxxxxxxxxxxxxxxxxxxxx'. how I could do it? 

my code
```
 ipfs.cat(''xxxxxxxxxxxxxxxxxxxxxxxxxxx'. ', function(err, res) {
            if (err || !res) {
                return console.error('ipfs cat error', err, res)
            }
            console.log(res) //  return array of numberes
            console.log(res.name)//should return filenam but return undifined
            $('#getValue').html(res.toString()) // return file content
        })
```

**Comment by its-VSP** [comment]
@yehia67 ipfs.cat(..) is to get the content of the file itself but not file with filename.
if you want to read the file by its name use MFS.

**Comment by yehia67** [comment]
Okay Thank you @its-VSP
