### ISSUE TITLE
How long will files be available for?

### ISSUE THREAD

**Issue by javaadpatel** [ipfs/interface-js-ipfs-core#543]
Hi, if i upload an image using `await node.addFromFs('./image.png')` how long will it be available on ipfs for? is there a way to refresh it if it expires?

**Comment by alanshaw** [comment]
Hi @javaadpatel please use the discussion forums for this sort of question https://discuss.ipfs.io/

When you add a file to ipfs you add it to your local repo. It will remain in your repo unless you "unpin" it. All files added to your IPFS node are "pinned" by default.

Anything in your local repo is available to any peer on the network.

If you unpin the file and run garbage collection on your repo it will be removed from your node but other nodes in the network may still have it in their repo. There is no way to remove the file from other node's repos and no expiry.
